"""initial migration

Revision ID: 57d41861ff67
Revises: 
Create Date: 2020-05-10 15:39:46.536051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d41861ff67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('users', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('channel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel')
    # ### end Alembic commands ###
